name: Whatsapp Web Dev Pipeline

on:
  push:
    branches:
      - dev-bare
  pull_request:
    branches:
      - dev-bare

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image to Docker Hub
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Recreate .env file from the base64 format in GitHub secrets
        run: echo "${{ secrets.BASE64_ENV }}" | base64 --decode > .env

      - name: Convert repository name to lowercase
        run: echo "IMAGE_NAME=${{ env.REGISTRY }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV


      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:cannot_read

      - name: Connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker login ghcr.io --username nzeakokosi7 --password ${{ secrets.GHCR_PAT }}
            docker pull ${{ env.IMAGE_NAME }}:cannot_read
